/*
 * Copyright (C) 2014 phramusca ( https://github.com/phramusca/JaMuz/ )
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package jamuz.gui;

import jamuz.FileInfoInt;
import jamuz.utils.Popup;
import jamuz.utils.StringManager;
import javax.swing.DefaultListModel;

/**
 *
 * @author phramusca ( https://github.com/phramusca/JaMuz/ )
 */


public class FramePlayerInfo extends javax.swing.JFrame {

    /**
     * Creates new form PlayerInfo
     * @param title
     * @param queueModel
     */
    public FramePlayerInfo(String title, ListModelPlayerQueue queueModel) {
        initComponents();
        this.setTitle(title);
        jListPlayerQueue.setModel(queueModel);
        
        //TODO: Increase jSliderPlayerLength thumb height for better display
//        jSliderPlayerLength.setUI(new MyCustonSliderUI());
//                
//        UIDefaults defaults = UIManager.getDefaults();
//        defaults.put("Slider.thumbHeight", 100); // change height
//        defaults.put("Slider.thumbWidth", 100); // change width
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPlayer = new javax.swing.JPanel();
        jPanelPlayerCover = new jamuz.gui.PanelCover();
        jLabelPlayerTimeTotal = new javax.swing.JLabel();
        jSliderPlayerLength = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPlayerQueue = new javax.swing.JList();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jPanelPlayer.setBackground(java.awt.Color.darkGray);

        jPanelPlayerCover.setBackground(java.awt.Color.darkGray);
        jPanelPlayerCover.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanelPlayerCover.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanelPlayerCover.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout jPanelPlayerCoverLayout = new javax.swing.GroupLayout(jPanelPlayerCover);
        jPanelPlayerCover.setLayout(jPanelPlayerCoverLayout);
        jPanelPlayerCoverLayout.setHorizontalGroup(
            jPanelPlayerCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPlayerCoverLayout.setVerticalGroup(
            jPanelPlayerCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelPlayerTimeEllapsed.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        jLabelPlayerTimeEllapsed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlayerTimeEllapsed.setText("00:00"); // NOI18N

        jLabelPlayerTimeTotal.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        jLabelPlayerTimeTotal.setText("00:00"); // NOI18N

        jSliderPlayerLength.setValue(0);
        jSliderPlayerLength.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderPlayerLength.setEnabled(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jListPlayerQueue.setBackground(java.awt.Color.darkGray);
        jListPlayerQueue.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jListPlayerQueue.setModel(new DefaultListModel());
        jListPlayerQueue.setAutoscrolls(false);
        jListPlayerQueue.setEnabled(false);
        jListPlayerQueue.setSelectionBackground(java.awt.Color.lightGray);
        jScrollPane1.setViewportView(jListPlayerQueue);

        javax.swing.GroupLayout jPanelPlayerLayout = new javax.swing.GroupLayout(jPanelPlayer);
        jPanelPlayer.setLayout(jPanelPlayerLayout);
        jPanelPlayerLayout.setHorizontalGroup(
            jPanelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPlayerLayout.createSequentialGroup()
                        .addComponent(jLabelPlayerTimeEllapsed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPlayerLength, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPlayerTimeTotal))
                    .addComponent(jPanelPlayerCover, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPlayerLayout.setVerticalGroup(
            jPanelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPlayerCover, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPlayerTimeEllapsed)
                        .addComponent(jSliderPlayerLength, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPlayerTimeTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        PanelMain.unsetToggleButtonPlayerInfo();
    }//GEN-LAST:event_formComponentHidden

    /**
     * display file info
     * @param myFileInfo
     */
    public void displayFileInfo(FileInfoInt myFileInfo) {
		try {
			PanelCover coverImg = (PanelCover) jPanelPlayerCover;
			coverImg.setImage(myFileInfo.getCoverImage(), true);
		} catch (Exception ex) {
			Popup.error(ex);
		}
	}
    
    /**
     * set selected in queue
     * @param index
     */
    public void setSelected(int index) {
        jListPlayerQueue.setSelectedIndex(index);
    }
    
    /**
     * display MP3 play position in slider
     * @param currentPosition
     */
    public void dispMP3progress(int currentPosition) {
        jSliderPlayerLength.setValue(currentPosition);
		jLabelPlayerTimeEllapsed.setText(StringManager.secondsToMMSS(currentPosition));
    }
    
    /**
     * display total time
     * @param maximum
     */
    public void setMax(int maximum) {
        jSliderPlayerLength.setMaximum(maximum);
		jLabelPlayerTimeTotal.setText(StringManager.secondsToMMSS(maximum));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static final javax.swing.JLabel jLabelPlayerTimeEllapsed = new javax.swing.JLabel();
    private static javax.swing.JLabel jLabelPlayerTimeTotal;
    private static javax.swing.JList jListPlayerQueue;
    private javax.swing.JPanel jPanelPlayer;
    public static javax.swing.JPanel jPanelPlayerCover;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JSlider jSliderPlayerLength;
    // End of variables declaration//GEN-END:variables
}
