/*
 * Copyright (C) 2014 phramusca ( https://github.com/phramusca/JaMuz/ )
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package jamuz.gui;

import jamuz.gui.swing.PanelPieChart;
import jamuz.DbConnJaMuz.StatItem;
import jamuz.process.check.FolderInfo;
import jamuz.Jamuz;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;
import java.util.Random;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JSlider;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import jamuz.gui.swing.TableModel;
import jamuz.utils.Inter;
import jamuz.utils.Popup;
import jamuz.utils.StringManager;

/**
 *
 * @author phramusca ( https://github.com/phramusca/JaMuz/ )
 */
public class PanelStats extends javax.swing.JPanel {

    private static TableModel tableModel;
    
    private static ArrayList<StatItem> stats = new ArrayList<>();
    private Color myColors[];
    
    /**
     * Creates new form PanelStats
     */
    public PanelStats() {
        initComponents();
    }
    
    /**
     * extended gui init
     */
    public void initExtended() {
		
		jSliderStatsNbCategories.setEnabled(false);
		jSliderStatsNbCategories.setValue(6);
		
		//Get table model
		tableModel = (TableModel) jTableStats.getModel();
		//Set model
		String[] columnNames = {"# file", "# album", "%", "Length", "Rating", "Size", ""};  //NOI18N
		Object[][] data = {
			{0, 0, 0, 0, 0, 0, "Default"}  //NOI18N
		};
		tableModel.setModel(columnNames, data);
		//Clear model
		tableModel.clear();

		TableColumn column;
		//Set "#" column width
		column = jTableStats.getColumnModel().getColumn(0);
		column.setMinWidth(100);
		column.setPreferredWidth(100);
	
		//Set "#" column width
		column = jTableStats.getColumnModel().getColumn(1);
		column.setMinWidth(100);
		column.setPreferredWidth(100);
		
        //Set "%" column width
		column = jTableStats.getColumnModel().getColumn(2);
		column.setMinWidth(40);
		column.setMaxWidth(40);

        //"Length"
        column = jTableStats.getColumnModel().getColumn(3);
		column.setMinWidth(170);
		column.setPreferredWidth(170);
        
        //"Rating"
        column = jTableStats.getColumnModel().getColumn(4);
		column.setMinWidth(50);
		column.setPreferredWidth(50);
        
        //"Size"
        column = jTableStats.getColumnModel().getColumn(5);
		column.setMinWidth(150);
		column.setPreferredWidth(150);
        
		//Set "Label" column width
		column = jTableStats.getColumnModel().getColumn(6);
//		column.setMinWidth(20);
		column.setPreferredWidth(500);
		
		//Define chart colors
		myColors = new Color [21];
        myColors [0]= new Color(255,80,5);
        myColors [1]= new Color(0,117,220);
        myColors [2]= new Color(153,63,0);
        myColors [3]= new Color(76,0,92);
        myColors [4]= new Color(25,25,25);
        myColors [5]= new Color(0,92,49);
        myColors [6]= new Color(43,206,72);
        myColors [7]= new Color(255,204,153);
        myColors [8]= new Color(128,128,128);
        myColors [9]= new Color(148,255,181);
        myColors [10]= new Color(143,124,0);
        myColors [11]= new Color(157,204,0);
        myColors [12]= new Color(194,0,136);
        myColors [13]= new Color(0,51,128);
        myColors [14]= new Color(255,164,5);
        myColors [15]= new Color(255,168,187);
        myColors [16]= new Color(66,102,0);
        myColors [17]= new Color(255,0,16);
        myColors [18]= new Color(94,241,242);
        myColors [19]= new Color(0,153,143);
        myColors [20]= new Color(224,255,102);
        
        //Set default radio button to display its stats
        jRadioStatRating.setSelected(true);
        isManual = true;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStat = new javax.swing.ButtonGroup();
        jSliderStatsNbCategories = new javax.swing.JSlider();
        jScrollPaneStats = new javax.swing.JScrollPane();
        jTableStats = new javax.swing.JTable();
        jPanelStatsChartBorder = new javax.swing.JPanel();
        jPanelStatsChart = new jamuz.gui.swing.PanelPieChart();
        jButtonStatsSelect = new javax.swing.JButton();
        jRadioStatRatedOnly = new javax.swing.JRadioButton();
        jRadioStatRating = new javax.swing.JRadioButton();
        jRadioStatCheckedOnly = new javax.swing.JRadioButton();
        jRadiotatStatus = new javax.swing.JRadioButton();
        jRadioStatGenre = new javax.swing.JRadioButton();
        jRadioStatYear = new javax.swing.JRadioButton();
        jRadioStatDecade = new javax.swing.JRadioButton();
        jRadioStatAlbum = new javax.swing.JRadioButton();
        jRadioStatArtist = new javax.swing.JRadioButton();
        jButtonRefresh = new javax.swing.JButton();
        jRadioStatPercentRated = new javax.swing.JRadioButton();
        jPanelSelectFilters = new javax.swing.JPanel();
        jPanelSelectStatus = new javax.swing.JPanel();
        jCheckBoxSelectCheckedFlag0 = new javax.swing.JCheckBox();
        jCheckBoxSelectCheckedFlag3 = new javax.swing.JCheckBox();
        jCheckBoxSelectCheckedFlag2 = new javax.swing.JCheckBox();
        jCheckBoxSelectCheckedFlag1 = new javax.swing.JCheckBox();
        jPanelSelectRating = new javax.swing.JPanel();
        jCheckBoxSelectRating0 = new javax.swing.JCheckBox();
        jCheckBoxSelectRating1 = new javax.swing.JCheckBox();
        jCheckBoxSelectRating2 = new javax.swing.JCheckBox();
        jCheckBoxSelectRating3 = new javax.swing.JCheckBox();
        jCheckBoxSelectRating4 = new javax.swing.JCheckBox();
        jCheckBoxSelectRating5 = new javax.swing.JCheckBox();

        jSliderStatsNbCategories.setMajorTickSpacing(10);
        jSliderStatsNbCategories.setMaximum(20);
        jSliderStatsNbCategories.setMinorTickSpacing(1);
        jSliderStatsNbCategories.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderStatsNbCategories.setPaintLabels(true);
        jSliderStatsNbCategories.setPaintTicks(true);
        jSliderStatsNbCategories.setSnapToTicks(true);
        jSliderStatsNbCategories.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStatsNbCategoriesStateChanged(evt);
            }
        });

        jTableStats.setModel(new jamuz.gui.swing.TableModel());
        jScrollPaneStats.setViewportView(jTableStats);

        jPanelStatsChartBorder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanelStatsChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelStatsChartLayout = new javax.swing.GroupLayout(jPanelStatsChart);
        jPanelStatsChart.setLayout(jPanelStatsChartLayout);
        jPanelStatsChartLayout.setHorizontalGroup(
            jPanelStatsChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelStatsChartLayout.setVerticalGroup(
            jPanelStatsChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelStatsChartBorderLayout = new javax.swing.GroupLayout(jPanelStatsChartBorder);
        jPanelStatsChartBorder.setLayout(jPanelStatsChartBorderLayout);
        jPanelStatsChartBorderLayout.setHorizontalGroup(
            jPanelStatsChartBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatsChartBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelStatsChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelStatsChartBorderLayout.setVerticalGroup(
            jPanelStatsChartBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatsChartBorderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelStatsChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jamuz/Bundle"); // NOI18N
        jButtonStatsSelect.setText(bundle.getString("Button.Select")); // NOI18N
        jButtonStatsSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatsSelectActionPerformed(evt);
            }
        });

        buttonGroupStat.add(jRadioStatRatedOnly);
        jRadioStatRatedOnly.setText(Inter.get("Stat.RatingRated")); // NOI18N
        jRadioStatRatedOnly.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadioStatRating);
        jRadioStatRating.setText(Inter.get("Stat.Rating")); // NOI18N
        jRadioStatRating.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadioStatCheckedOnly);
        jRadioStatCheckedOnly.setText(Inter.get("Stat.CheckedChecked")); // NOI18N
        jRadioStatCheckedOnly.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadiotatStatus);
        jRadiotatStatus.setText(Inter.get("Stat.Checked")); // NOI18N
        jRadiotatStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadioStatGenre);
        jRadioStatGenre.setText(Inter.get("Tag.Genre")); // NOI18N
        jRadioStatGenre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadioStatYear);
        jRadioStatYear.setText(Inter.get("Tag.Year")); // NOI18N
        jRadioStatYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadioStatDecade);
        jRadioStatDecade.setText(Inter.get("Stat.Decade")); // NOI18N
        jRadioStatDecade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadioStatAlbum);
        jRadioStatAlbum.setText(Inter.get("Tag.Album")); // NOI18N
        jRadioStatAlbum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        buttonGroupStat.add(jRadioStatArtist);
        jRadioStatArtist.setText(Inter.get("Tag.Artist")); // NOI18N
        jRadioStatArtist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/update.png"))); // NOI18N
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        buttonGroupStat.add(jRadioStatPercentRated);
        jRadioStatPercentRated.setText(Inter.get("Stat.PercentRated")); // NOI18N
        jRadioStatPercentRated.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemChanged(evt);
            }
        });

        jPanelSelectStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBoxSelectCheckedFlag0.setText("?"); // NOI18N
        jCheckBoxSelectCheckedFlag0.setEnabled(false);
        jCheckBoxSelectCheckedFlag0.setOpaque(true);

        jCheckBoxSelectCheckedFlag3.setSelected(true);
        jCheckBoxSelectCheckedFlag3.setText(Inter.get("Check.OK")); // NOI18N
        jCheckBoxSelectCheckedFlag3.setEnabled(false);
        jCheckBoxSelectCheckedFlag3.setOpaque(true);

        jCheckBoxSelectCheckedFlag2.setSelected(true);
        jCheckBoxSelectCheckedFlag2.setText(Inter.get("Check.OK")); // NOI18N
        jCheckBoxSelectCheckedFlag2.setEnabled(false);
        jCheckBoxSelectCheckedFlag2.setOpaque(true);

        jCheckBoxSelectCheckedFlag1.setText(Inter.get("Check.KO")); // NOI18N
        jCheckBoxSelectCheckedFlag1.setEnabled(false);
        jCheckBoxSelectCheckedFlag1.setOpaque(true);

        javax.swing.GroupLayout jPanelSelectStatusLayout = new javax.swing.GroupLayout(jPanelSelectStatus);
        jPanelSelectStatus.setLayout(jPanelSelectStatusLayout);
        jPanelSelectStatusLayout.setHorizontalGroup(
            jPanelSelectStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSelectStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSelectStatusLayout.createSequentialGroup()
                        .addComponent(jCheckBoxSelectCheckedFlag0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxSelectCheckedFlag3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelectStatusLayout.createSequentialGroup()
                        .addComponent(jCheckBoxSelectCheckedFlag1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxSelectCheckedFlag2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSelectStatusLayout.setVerticalGroup(
            jPanelSelectStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectStatusLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanelSelectStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSelectCheckedFlag0)
                    .addComponent(jCheckBoxSelectCheckedFlag3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanelSelectStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSelectCheckedFlag2)
                    .addComponent(jCheckBoxSelectCheckedFlag1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelSelectRating.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBoxSelectRating0.setSelected(true);
        jCheckBoxSelectRating0.setText("?"); // NOI18N
        jCheckBoxSelectRating0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterItemStateChanged(evt);
            }
        });

        jCheckBoxSelectRating1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/1starU.png"))); // NOI18N
        jCheckBoxSelectRating1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/1starC.png"))); // NOI18N
        jCheckBoxSelectRating1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterItemStateChanged(evt);
            }
        });

        jCheckBoxSelectRating2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/2starU.png"))); // NOI18N
        jCheckBoxSelectRating2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/2starC.png"))); // NOI18N
        jCheckBoxSelectRating2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterItemStateChanged(evt);
            }
        });

        jCheckBoxSelectRating3.setSelected(true);
        jCheckBoxSelectRating3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/3starU.png"))); // NOI18N
        jCheckBoxSelectRating3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/3starC.png"))); // NOI18N
        jCheckBoxSelectRating3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterItemStateChanged(evt);
            }
        });

        jCheckBoxSelectRating4.setSelected(true);
        jCheckBoxSelectRating4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/4starU.png"))); // NOI18N
        jCheckBoxSelectRating4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/4starC.png"))); // NOI18N
        jCheckBoxSelectRating4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterItemStateChanged(evt);
            }
        });

        jCheckBoxSelectRating5.setSelected(true);
        jCheckBoxSelectRating5.setToolTipText("");
        jCheckBoxSelectRating5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/5starU.png"))); // NOI18N
        jCheckBoxSelectRating5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/5star.png"))); // NOI18N
        jCheckBoxSelectRating5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelSelectRatingLayout = new javax.swing.GroupLayout(jPanelSelectRating);
        jPanelSelectRating.setLayout(jPanelSelectRatingLayout);
        jPanelSelectRatingLayout.setHorizontalGroup(
            jPanelSelectRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectRatingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSelectRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSelectRating2)
                    .addComponent(jCheckBoxSelectRating0)
                    .addComponent(jCheckBoxSelectRating1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSelectRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSelectRating3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxSelectRating4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxSelectRating5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelSelectRatingLayout.setVerticalGroup(
            jPanelSelectRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectRatingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSelectRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSelectRatingLayout.createSequentialGroup()
                        .addComponent(jCheckBoxSelectRating0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSelectRating1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSelectRating2))
                    .addGroup(jPanelSelectRatingLayout.createSequentialGroup()
                        .addComponent(jCheckBoxSelectRating5)
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBoxSelectRating4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSelectRating3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSelectFiltersLayout = new javax.swing.GroupLayout(jPanelSelectFilters);
        jPanelSelectFilters.setLayout(jPanelSelectFiltersLayout);
        jPanelSelectFiltersLayout.setHorizontalGroup(
            jPanelSelectFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectFiltersLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanelSelectFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSelectRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSelectStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanelSelectFiltersLayout.setVerticalGroup(
            jPanelSelectFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectFiltersLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelSelectRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSelectStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioStatRating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioStatPercentRated))
                            .addComponent(jRadioStatRatedOnly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadiotatStatus)
                            .addComponent(jRadioStatCheckedOnly))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioStatDecade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioStatYear))
                            .addComponent(jRadioStatGenre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioStatAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioStatArtist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSelectFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneStats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                            .addComponent(jPanelStatsChartBorder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSliderStatsNbCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonStatsSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioStatRating)
                            .addComponent(jRadiotatStatus)
                            .addComponent(jRadioStatGenre)
                            .addComponent(jRadioStatPercentRated)
                            .addComponent(jRadioStatArtist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioStatRatedOnly)
                            .addComponent(jRadioStatCheckedOnly)
                            .addComponent(jRadioStatDecade)
                            .addComponent(jRadioStatYear)
                            .addComponent(jRadioStatAlbum)))
                    .addComponent(jButtonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSliderStatsNbCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStatsSelect))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelStatsChartBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSelectFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addComponent(jScrollPaneStats, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonStatsSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatsSelectActionPerformed

        //Getting selected File
        int selectedRow = jTableStats.getSelectedRow();
        if (selectedRow >= 0) {
            //convert to model index (as sortable model)
            selectedRow = jTableStats.convertRowIndexToModel(selectedRow);
            
            String stat = getSelectedButtonText(buttonGroupStat);
            String label = stats.get(selectedRow).getLabel();
            String field;
            
            //Set selected
            if(stat.equals(Inter.get("Tag.Genre"))) { //NOI18N
                field="genre";
            }
            else if(stat.equals(Inter.get("Tag.Artist"))) { //NOI18N
                field="artist";
            }
            else if(stat.equals(Inter.get("Tag.Album"))) { //NOI18N
                field="album";
            }
            else {
                field="toto";
                //TODO This should not happen. Anyway would be better to use a common Enum somehow
            }
            PanelSelect.setSelected(field, label);
        } else {
            Popup.warning(Inter.get("Error.YouMustSelectArow")); 		  //NOI18N
        }
    }//GEN-LAST:event_jButtonStatsSelectActionPerformed

    //False by default as jSliderStatsNbCategories is set to 0 within 
    //GUI auto-generated code, and it is an internal hange
    private static boolean isManual = false;
    
    private void jSliderStatsNbCategoriesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStatsNbCategoriesStateChanged
        JSlider source = (JSlider) evt.getSource();
//        int position = (int) source.getValue();
        if (!source.getValueIsAdjusting()) {
            if(isManual) { //before panel init completes
                showStatsChartPie(false);
            }
        }
    }//GEN-LAST:event_jSliderStatsNbCategoriesStateChanged

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        showStatsChartPie();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void filterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterItemStateChanged
        showStatsChartPie();
    }//GEN-LAST:event_filterItemStateChanged

    private void radioItemChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioItemChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {	
            showStatsChartPie();
        }
    }//GEN-LAST:event_radioItemChanged

    private void fillStatTable(String field, String title, ArrayList<StatItem> stats, 
			boolean showChart, boolean[] selRatings) {
		jTableStats.setRowSorter(null);
		tableModel.clear();
		String totalSelector;
        String table="file"; //NOI18N
        switch (field) {
            case "checked": //NOI18N
                //NOI18N
                totalSelector=">="+stats.get(0).getValue();  //NOI18N
                table="path"; //NOI18N
                break;
            case "rating": //NOI18N
                //NOI18N
                totalSelector=">="+stats.get(0).getLabel();  //NOI18N
                break;
            default:
                totalSelector="%";  //NOI18N
                break;
        }

        StatItem total=Jamuz.getDb().getStatItem(field, totalSelector, 
				table, "", Color.YELLOW, selRatings);
        long totalCount = total.getCountFile();

        float percentage;
		ArrayList<PanelPieChart.PieSlice> slices = new ArrayList<>();
		for (StatItem statItem : stats) {
			if(totalCount>0) {
				percentage = statItem.getCountFile() * 100 / totalCount;
			}
			else {
				percentage = 0;
			}
            statItem.setPercentage(percentage);
			this.addRowStats(tableModel, statItem);
			slices.add(new PanelPieChart.PieSlice(statItem.getLabelForChart()+"\t ("+String.valueOf((int)percentage)+"%)", (double) statItem.getCountFile(), statItem.getColor()));  //NOI18N
		}
        
        if(showChart) {
            createChart(title, totalCount, slices);
        }

		//Enable row tableSorter (cannot be done if model is empty)
		if(tableModel.getRowCount()>0) {
			//Enable auto sorter
			jTableStats.setAutoCreateRowSorter(true);
			//Sort by action, result
			TableRowSorter<TableModel> tableSorter = new TableRowSorter<>(tableModel);
			jTableStats.setRowSorter(tableSorter);
			List <RowSorter.SortKey> sortKeys = new ArrayList<>();
			sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
			sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
			tableSorter.setSortKeys(sortKeys);
		}
		else {
			jTableStats.setAutoCreateRowSorter(false);
		}
	}
	
    private void createChart(String title, long total, ArrayList<PanelPieChart.PieSlice> slices) {

		//Sort the list by decreasing value
		Collections.sort(slices);
		
		//Merge minor categories "Other" as requested
		int nbFiles=stats.size();
		if(nbFiles>jSliderStatsNbCategories.getValue()) {
			double otherValue=0;
			ArrayList<PanelPieChart.PieSlice> slicesToDisplay = new ArrayList<>();
			
			for(int i = 0; i < jSliderStatsNbCategories.getValue(); i++) {
				slicesToDisplay.add(slices.get(i));
			}
			//TODO: get subarray instead of recreating another list
			//slices=(ArrayList)slices.subList(0, NbCategories);
			for(int i = jSliderStatsNbCategories.getValue(); i < nbFiles; i++) {
				otherValue+=slices.get(i).getValue();
			}
			float percentage = (float) otherValue * 100 / total;
			slicesToDisplay.add(new PanelPieChart.PieSlice(Inter.get("Label.Other")+"\t ("+String.valueOf((int)percentage)+"%)", otherValue, Color.WHITE));  //NOI18N
			slices=slicesToDisplay;
		}

        Random generator = new Random();
		Color newColor;
		//Add color, now that it is sorted
		for(int i = 0; i < slices.size(); i++) {
			if(slices.get(i).getColor()==null) {
                if(i<myColors.length) {
                    newColor = myColors[i]; 
                }
                else {
                    newColor = new Color(generator.nextInt(256),generator.nextInt(256),generator.nextInt(256)); 
                }
                slices.get(i).setColor(newColor);
            }
		}

		//Create and display chart pie
		PanelPieChart myCharPie = (PanelPieChart) jPanelStatsChart;
		myCharPie.setPie(title, slices);
    }
    
	private void addToStats(String field, String value, Color color) {
		addToStats(field, value, value, color);
	}
	
    private void addRowStats(TableModel myTableModel, StatItem statItem) {
		Object[] donnee = new Object[]{statItem.getCountFile(), statItem.getCountPath(), statItem.getPercentage(), StringManager.humanReadableSeconds(statItem.getLength()), 
            statItem.getRating(), StringManager.humanReadableByteCount(statItem.getSize(), false), statItem.getLabelForChart()};
		myTableModel.addRow(donnee);
    }
    
	private void addToStats(String field, String value, String label, 
			Color color) {
		String table="file";  //NOI18N
		if(field.equals("checked")) {  //NOI18N
			table="path";  //NOI18N
		}
		stats.add(Jamuz.getDb().getStatItem(field, value, table, label, color, null));
	}
	
    private String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
    private void setDefaultNbCategories() {
        jSliderStatsNbCategories.setEnabled(false);
        setDefaultNbCategories(stats.size(), true);
    }
    
    private void setDefaultNbCategories(int size, boolean setSlider) {
        if(setSlider) {
            isManual = false;
            jSliderStatsNbCategories.setValue(size); 		
            isManual = true;
        }
    }
    
    private void showStatsChartPie() {
        showStatsChartPie(true);
    }
    
	private void showStatsChartPie(boolean setSlider) {
       
		boolean[] selRatingsToUse = null;
		boolean[] selRatings = new boolean[6]; 
        selRatings[0]=jCheckBoxSelectRating0.isSelected();
        selRatings[1]=jCheckBoxSelectRating1.isSelected();
        selRatings[2]=jCheckBoxSelectRating2.isSelected();
        selRatings[3]=jCheckBoxSelectRating3.isSelected();
        selRatings[4]=jCheckBoxSelectRating4.isSelected();
        selRatings[5]=jCheckBoxSelectRating5.isSelected();
		
		boolean oneSelected=false;
		for (int i = 0; i < selRatings.length; i++) {
            if (selRatings[i]) {
                oneSelected=true;
				break;
            }
        }
		if(!oneSelected) {
			Popup.warning("Select at least one rating");
			return;
		}
		
		//FIXME LOW STATS Use status filters when applicable
		
        String stat = getSelectedButtonText(buttonGroupStat);
        
		if(stat.equals(Inter.get("Tag.Genre")) 
				|| stat.equals(Inter.get("Tag.Artist")) 
				|| stat.equals(Inter.get("Tag.Album"))) {  //NOI18N
			jButtonStatsSelect.setVisible(true);
		}
		else {
			jButtonStatsSelect.setVisible(false);
		}
		stats = new ArrayList<>();
        
        boolean showChart=false;
		boolean showFilters=true;
        jSliderStatsNbCategories.setEnabled(true);
        
        String field="";  //NOI18N
        //TODO: Replace if, else if by an enum switch
		if(stat.equals(Inter.get("Stat.Rating"))) { //NOI18N
			field="rating";  //NOI18N
			addToStats(field, "0", Color.WHITE);  //NOI18N
			addToStats(field, "1", Color.RED);  //NOI18N
			addToStats(field, "2", Color.LIGHT_GRAY);  //NOI18N
			addToStats(field, "3", new Color(0,117,220));  //NOI18N
			addToStats(field, "4", new Color(0,92,49));  //NOI18N
			addToStats(field, "5", new Color(43,206,72));  //NOI18N
            showChart=true;
			showFilters=false;
            setDefaultNbCategories();
		}
		else if(stat.equals(Inter.get("Stat.RatingRated"))) { //NOI18N
			field="rating";  //NOI18N
            addToStats(field, "1", Color.RED);  //NOI18N
			addToStats(field, "2", Color.LIGHT_GRAY);  //NOI18N
			addToStats(field, "3", new Color(0,117,220));  //NOI18N
			addToStats(field, "4", new Color(0,92,49));  //NOI18N
			addToStats(field, "5", new Color(43,206,72));  //NOI18N
            showChart=true;
			showFilters=false;
            setDefaultNbCategories();
		}
		else if(stat.equals(Inter.get("Stat.Checked"))) { //NOI18N
			field="checked";  //NOI18N
			for(FolderInfo.CheckedFlag checkedFlag : FolderInfo.CheckedFlag.values()) {
				addToStats(field, String.valueOf(checkedFlag.getValue()), checkedFlag.toString(), checkedFlag.getColor());
			}
            showChart=true;
			showFilters=false;
            setDefaultNbCategories();
		}
        else if(stat.equals(Inter.get("Stat.CheckedChecked"))) { //NOI18N
			field="checked";  //NOI18N
			for(FolderInfo.CheckedFlag checkedFlag : FolderInfo.CheckedFlag.values()) {
				if(!checkedFlag.equals(FolderInfo.CheckedFlag.UNCHECKED)) {
                    addToStats(field, String.valueOf(checkedFlag.getValue()), checkedFlag.toString(), checkedFlag.getColor());
                }
			}
            showChart=true;
			showFilters=false;
            setDefaultNbCategories();
		}
        else if(stat.equals(Inter.get("Stat.PercentRated"))) {
            field="idPath"; //Any field from path will do as =%
            Jamuz.getDb().getPercentRatedForStats(stats);
            showChart=true;
			showFilters=false;
            setDefaultNbCategories();
        }
		else if(stat.equals(Inter.get("Tag.Genre"))) { //NOI18N
			field="genre";  //NOI18N
			selRatingsToUse=selRatings;
			Jamuz.getDb().getSelectionList4Stats(stats, field, selRatings);
            showChart=true;
            setDefaultNbCategories(10, setSlider);
		}
		else if(stat.equals(Inter.get("Tag.Year"))) { //NOI18N
			field="year";  //NOI18N
			selRatingsToUse=selRatings;
			Jamuz.getDb().getSelectionList4Stats(stats, field, selRatings);
            showChart=true;
            setDefaultNbCategories(10, setSlider);
		}
		else if(stat.equals(Inter.get("Tag.Artist"))) { //NOI18N
			field="artist";  //NOI18N
			selRatingsToUse=selRatings;
			Jamuz.getDb().getSelectionList4Stats(stats, field, selRatings);
		}
		else if(stat.equals(Inter.get("Tag.Album"))) { //NOI18N
			field="album";  //NOI18N
			selRatingsToUse=selRatings;
            Jamuz.getDb().getSelectionList4Stats(stats, field, selRatings);
		}
		else if(stat.equals(Inter.get("Stat.Decade"))) { //NOI18N
			field="year";  //NOI18N
			addToStats(field, "", null);  //NOI18N
			for(int i = 190; i < 202; i++) {
				addToStats(field, Integer.toString(i)+"%", null);  //NOI18N
			}
            showChart=true;
			showFilters=false;
            setDefaultNbCategories();
		}
		else {
			//This should never happen (at least in prod) as we have a fixed list
			Popup.warning("Unknown required stat \""+stat+"\""); //NOI18N
		}
		
		jPanelSelectFilters.setVisible(showFilters); 
		jPanelStatsChartBorder.setVisible(showChart); 
        jSliderStatsNbCategories.setVisible(showChart); 
		
		fillStatTable(field, stat, stats, showChart, selRatingsToUse);
	}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupStat;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonStatsSelect;
    private static javax.swing.JCheckBox jCheckBoxSelectCheckedFlag0;
    private static javax.swing.JCheckBox jCheckBoxSelectCheckedFlag1;
    private static javax.swing.JCheckBox jCheckBoxSelectCheckedFlag2;
    private static javax.swing.JCheckBox jCheckBoxSelectCheckedFlag3;
    private static javax.swing.JCheckBox jCheckBoxSelectRating0;
    private static javax.swing.JCheckBox jCheckBoxSelectRating1;
    private static javax.swing.JCheckBox jCheckBoxSelectRating2;
    private static javax.swing.JCheckBox jCheckBoxSelectRating3;
    private static javax.swing.JCheckBox jCheckBoxSelectRating4;
    private static javax.swing.JCheckBox jCheckBoxSelectRating5;
    private javax.swing.JPanel jPanelSelectFilters;
    private static javax.swing.JPanel jPanelSelectRating;
    private static javax.swing.JPanel jPanelSelectStatus;
    private javax.swing.JPanel jPanelStatsChart;
    private javax.swing.JPanel jPanelStatsChartBorder;
    private javax.swing.JRadioButton jRadioStatAlbum;
    private javax.swing.JRadioButton jRadioStatArtist;
    private javax.swing.JRadioButton jRadioStatCheckedOnly;
    private javax.swing.JRadioButton jRadioStatDecade;
    private javax.swing.JRadioButton jRadioStatGenre;
    private javax.swing.JRadioButton jRadioStatPercentRated;
    private javax.swing.JRadioButton jRadioStatRatedOnly;
    private javax.swing.JRadioButton jRadioStatRating;
    private javax.swing.JRadioButton jRadioStatYear;
    private javax.swing.JRadioButton jRadiotatStatus;
    private javax.swing.JScrollPane jScrollPaneStats;
    private javax.swing.JSlider jSliderStatsNbCategories;
    private javax.swing.JTable jTableStats;
    // End of variables declaration//GEN-END:variables
}
