title: Jamuz
description: Music library manager, player and more
# https://pages.github.com/themes/
# theme: jekyll-theme-leap-day
# theme: minima
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: 
show_downloads: false
github:
  zip_url: https://github.com/phramusca/JaMuz/archive/master.zip
  tar_url: https://github.com/phramusca/JaMuz/archive/master.tar.gz
