title: Jamuz
description: Music management tool
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day
github:
  zip_url: https://github.com/phramusca/JaMuz/archive/master.zip
  tar_url: https://github.com/phramusca/JaMuz/archive/master.tar.gz
