/*
 * Copyright (C) 2019 phramusca ( https://github.com/phramusca/ )
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jamuz.process.check;

import jamuz.player.DialogPlayer;
import jamuz.utils.Inter;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author phramusca ( https://github.com/phramusca/ )
 */
public class DialogDuplicate extends javax.swing.JDialog {

	private final DuplicateInfo duplicateInfo;
	private final ICallBackCheck callback;
	
	/**
	 * Creates new form DialogDuplicate
	 * @param parent
	 * @param modal
	 * @param folder
	 * @param duplicateInfo
	 * @param callback
	 */
	public DialogDuplicate(java.awt.Frame parent, boolean modal, 
			FolderInfo folder, DuplicateInfo duplicateInfo, ICallBackCheck callback) {
		super(parent, modal);
		initComponents();
		this.duplicateInfo=duplicateInfo;
		if(folder!=null) {
			
			jLabelCheckStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/"+folder.action.getRes())));
			jLabelCheckStatus.setBackground(folder.action.getColor());
			jLabelCheckStatus.setText("<html><b>Folder being checked: "+folder.action.toString()+"<b></html>");
			panelDuplicate1.init(folder, duplicateInfo, (DuplicateInfo duplicateInfo1) -> {
				if(duplicateInfo1!=null) {
					initPanel2(duplicateInfo1);
				}
			});
		}
		if(duplicateInfo!=null) {
			initPanel2(duplicateInfo);
		}
		this.callback = callback;
	}
		
	private void initPanel2(DuplicateInfo duplicateInfo) {
		jLabelCheckStatusDuplicate.setBackground(duplicateInfo.getFolderInfo().getCheckedFlag().getColor());
		jLabelCheckStatusDuplicate.setText("<html><b>Potential duplicate: "+duplicateInfo.getFolderInfo().getCheckedFlag().toString()+"<b></html>");
		panelDuplicate2.init(duplicateInfo);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelCheckStatus = new javax.swing.JLabel();
        panelDuplicate1 = new jamuz.process.check.PanelDuplicate();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelCheckStatusDuplicate = new javax.swing.JLabel();
        panelDuplicate2 = new jamuz.process.check.PanelDuplicate();
        jButtonNoDuplicate = new javax.swing.JButton();
        jButtonCheckDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setResizeWeight(0.5);

        jLabelCheckStatus.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckStatus.setText(" "); // NOI18N
        jLabelCheckStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckStatus.setOpaque(true);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDuplicate1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCheckStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckStatus)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDuplicate1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabelCheckStatusDuplicate.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckStatusDuplicate.setText(" "); // NOI18N
        jLabelCheckStatusDuplicate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckStatusDuplicate.setOpaque(true);

        jButtonNoDuplicate.setText("Not a duplicate");
        jButtonNoDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoDuplicateActionPerformed(evt);
            }
        });

        jButtonCheckDelete.setBackground(java.awt.Color.black);
        jButtonCheckDelete.setForeground(java.awt.Color.white);
        jButtonCheckDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jamuz/ressources/bin.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jamuz/Bundle"); // NOI18N
        jButtonCheckDelete.setText(bundle.getString("Button.Delete")); // NOI18N
        jButtonCheckDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCheckStatusDuplicate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCheckDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNoDuplicate)
                .addContainerGap())
            .addComponent(panelDuplicate2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckStatusDuplicate)
                    .addComponent(jButtonNoDuplicate)
                    .addComponent(jButtonCheckDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDuplicate2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNoDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoDuplicateActionPerformed
        int n = JOptionPane.showConfirmDialog(
            null, Inter.get("Question.Check.CleanDuplicate"),  //NOI18N
            Inter.get("Label.Confirm"),  //NOI18N
            JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
			callback.notAduplicate();
			this.dispose();
        }
    }//GEN-LAST:event_jButtonNoDuplicateActionPerformed

    private void jButtonCheckDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckDeleteActionPerformed
        int n = JOptionPane.showConfirmDialog(
            null, Inter.get("Question.Check.DeleteFolderContent"),  //NOI18N
            Inter.get("Label.Confirm"),  //NOI18N
            JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            duplicateInfo.getFolderInfo().delete(panelDuplicate2.getProgressBar());
			panelDuplicate2.init(duplicateInfo.getFolderInfo(), null, (DuplicateInfo di) -> {});
			callback.notAduplicate();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCheckDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogPlayer.main(duplicateInfo.getFolderInfo().getFilesAudio().get(0));
    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param parentSize
	 * @param folder
	 * @param duplicateInfo
	 * @param callback
	 */
	public static void main(Dimension parentSize, FolderInfo folder, 
			DuplicateInfo duplicateInfo, ICallBackCheck callback) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogDuplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		
		//</editor-fold>

		DialogDuplicate dialog = new DialogDuplicate(new JFrame(), true, folder, 
				duplicateInfo, callback);
				
        //Set dialog size to x% of parent size
        parentSize.height = parentSize.height * 85/100;
        parentSize.width = parentSize.width * 95/100;
        dialog.setSize(parentSize);
        //Center the dialog on screen
        dialog.setLocationRelativeTo(dialog.getParent());
        //Display
        dialog.setVisible(true);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCheckDelete;
    private javax.swing.JButton jButtonNoDuplicate;
    private javax.swing.JLabel jLabelCheckStatus;
    private javax.swing.JLabel jLabelCheckStatusDuplicate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private jamuz.process.check.PanelDuplicate panelDuplicate1;
    private jamuz.process.check.PanelDuplicate panelDuplicate2;
    // End of variables declaration//GEN-END:variables
}
