/*
 * Copyright (C) 2014 phramusca ( https://github.com/phramusca/JaMuz/ )
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package jamuz.process.check;

import jamuz.Jamuz;
import jamuz.gui.swing.ProgressBar;
import jamuz.utils.Inter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author phramusca ( https://github.com/phramusca/JaMuz/ )
 */
public class PanelDuplicate extends javax.swing.JPanel {

	private CheckDisplay checkDisplay;
	private final ProgressBar progressBar;
	private DuplicateInfo duplicateInfo=null;
	
    /**
     * Creates new form PanelLyrics
     */
    public PanelDuplicate() {
        initComponents();
		progressBar = (ProgressBar)jProgressBarCheckDialog;
    }
    
	void init(FolderInfo folderInfo, DuplicateInfo diToSelect, ICallBackDuplicate callback) {
		this.duplicateInfo = diToSelect;
		jComboBoxCheckDuplicates.addActionListener((java.awt.event.ActionEvent evt) -> {
			if(checkDisplay.enableCombo) {
				callback.duplicate((DuplicateInfo) jComboBoxCheckDuplicates.getSelectedItem());
			}
		});
		new Thread("Thread.PanelDuplicate.init folder") {
			@Override
			public void run() {
				display(folderInfo);
			}
		}.start();
	}
	
	void init(DuplicateInfo duplicateInfo) {
		new Thread("Thread.PanelDuplicate.init duplicate") {
			@Override
			public void run() {
				FolderInfo folderInfo = duplicateInfo.getFolderInfo();
				folderInfo.browse(false, true, progressBar);
				try {
					folderInfo.analyse(progressBar);
					folderInfo.analyseMatch(0, progressBar); //Analyse first match
				} catch (CloneNotSupportedException ex) {
					Logger.getLogger(DialogDuplicate.class.getName()).log(Level.SEVERE, null, ex);
				}
				folderInfo.analyseMatchTracks();
				folderInfo.setAction(); 
				(progressBar).reset();
				display(folderInfo);
			}
		}.start();
	}
	
	private void display(FolderInfo folderInfo) {
		checkDisplay = new CheckDisplay(folderInfo, progressBar, jCheckBoxCheckAlbumArtistDisplay, jCheckBoxCheckAlbumDisplay, jCheckBoxCheckArtistDisplay, jCheckBoxCheckBPMDisplay, jCheckBoxCheckBitRateDisplay, jCheckBoxCheckCommentDisplay, jCheckBoxCheckCoverDisplay, jCheckBoxCheckFormatDisplay, jCheckBoxCheckGenreDisplay, jCheckBoxCheckLengthDisplay, jCheckBoxCheckSizeDisplay, jCheckBoxCheckYearDisplay, jCheckCheckTitleDisplay, jLabelCheckAlbumArtistTag, jLabelCheckAlbumTag, jLabelCheckNbTracks, jLabelCheckYearTag, jLabelCheckDesc, jLabelCheckID3v1Tag, jLabelCheckMeanBitRateTag, jLabelCheckNbFiles, jLabelCheckReplayGainTag, jLabelCheckGenre, jLabelCoverInfo, jPanelCheckCoverThumb, jScrollPaneCheckTags, jTableCheck, jComboBoxCheckDuplicates, jComboBoxCheckMatches);
		checkDisplay.displayFolder();
		
	}
	
	ProgressBar getProgressBar() {
		return progressBar;
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCheckCoverThumb = new jamuz.gui.PanelCover();
        jPanel8 = new javax.swing.JPanel();
        jCheckBoxCheckAlbumDisplay = new javax.swing.JCheckBox();
        jCheckBoxCheckAlbumArtistDisplay = new javax.swing.JCheckBox();
        jLabelCheckAlbumArtistTag = new javax.swing.JLabel();
        jLabelCheckAlbumTag = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxCheckFormatDisplay = new javax.swing.JCheckBox();
        jCheckBoxCheckLengthDisplay = new javax.swing.JCheckBox();
        jCheckBoxCheckSizeDisplay = new javax.swing.JCheckBox();
        jCheckBoxCheckBitRateDisplay = new javax.swing.JCheckBox();
        jLabelCheckMeanBitRateTag = new javax.swing.JLabel();
        jCheckBoxCheckBPMDisplay = new javax.swing.JCheckBox();
        jCheckBoxCheckCommentDisplay = new javax.swing.JCheckBox();
        jLabelCheckReplayGain = new javax.swing.JLabel();
        jLabelCheckReplayGainTag = new javax.swing.JLabel();
        jLabelCheckID3v1 = new javax.swing.JLabel();
        jLabelCheckID3v1Tag = new javax.swing.JLabel();
        jCheckBoxCheckYearDisplay = new javax.swing.JCheckBox();
        jCheckBoxCheckGenreDisplay = new javax.swing.JCheckBox();
        jLabelCheckYearTag = new javax.swing.JLabel();
        jLabelCheckGenre = new javax.swing.JLabel();
        jLabelCheckNbTracks = new javax.swing.JLabel();
        jLabelCheckNbFiles = new javax.swing.JLabel();
        jCheckCheckTitleDisplay = new javax.swing.JCheckBox();
        jCheckBoxCheckArtistDisplay = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabelCoverInfo = new javax.swing.JLabel();
        jCheckBoxCheckCoverDisplay = new javax.swing.JCheckBox();
        jLabelCheckDesc = new javax.swing.JLabel();
        jScrollPaneCheckTags = new javax.swing.JScrollPane();
        jTableCheck = new jamuz.gui.swing.TableHorizontal();
        jProgressBarCheckDialog = new jamuz.gui.swing.ProgressBar();
        jComboBoxCheckMatches = new javax.swing.JComboBox();
        jComboBoxCheckDuplicates = new javax.swing.JComboBox();

        jPanelCheckCoverThumb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCheckCoverThumb.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanelCheckCoverThumb.setMinimumSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanelCheckCoverThumbLayout = new javax.swing.GroupLayout(jPanelCheckCoverThumb);
        jPanelCheckCoverThumb.setLayout(jPanelCheckCoverThumbLayout);
        jPanelCheckCoverThumbLayout.setHorizontalGroup(
            jPanelCheckCoverThumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanelCheckCoverThumbLayout.setVerticalGroup(
            jPanelCheckCoverThumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        jPanel8.setBackground(java.awt.Color.lightGray);
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCheckAlbumArtistTag.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckAlbumArtistTag.setText(" "); // NOI18N
        jLabelCheckAlbumArtistTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckAlbumArtistTag.setOpaque(true);

        jLabelCheckAlbumTag.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckAlbumTag.setText(" "); // NOI18N
        jLabelCheckAlbumTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckAlbumTag.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jCheckBoxCheckAlbumDisplay)
                        .addGap(1, 1, 1)
                        .addComponent(jLabelCheckAlbumTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jCheckBoxCheckAlbumArtistDisplay)
                        .addGap(2, 2, 2)
                        .addComponent(jLabelCheckAlbumArtistTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCheckAlbumArtistDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCheckAlbumArtistTag, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCheckAlbumDisplay)
                    .addComponent(jLabelCheckAlbumTag))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.Color.lightGray);
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jamuz/Bundle"); // NOI18N
        jCheckBoxCheckFormatDisplay.setText(bundle.getString("Tag.Format")); // NOI18N

        jCheckBoxCheckLengthDisplay.setText(bundle.getString("Tag.Length")); // NOI18N

        jCheckBoxCheckSizeDisplay.setText(bundle.getString("Tag.Size")); // NOI18N

        jCheckBoxCheckBitRateDisplay.setText(bundle.getString("Tag.BitRate")); // NOI18N

        jLabelCheckMeanBitRateTag.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckMeanBitRateTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckMeanBitRateTag.setText("999"); // NOI18N
        jLabelCheckMeanBitRateTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckMeanBitRateTag.setOpaque(true);

        jCheckBoxCheckBPMDisplay.setText(bundle.getString("Tag.BPM")); // NOI18N

        jCheckBoxCheckCommentDisplay.setText(bundle.getString("Tag.Comment")); // NOI18N

        jLabelCheckReplayGain.setText("ReplayGain"); // NOI18N

        jLabelCheckReplayGainTag.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckReplayGainTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckReplayGainTag.setText("yes"); // NOI18N
        jLabelCheckReplayGainTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckReplayGainTag.setOpaque(true);

        jLabelCheckID3v1.setText("ID3v1"); // NOI18N

        jLabelCheckID3v1Tag.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckID3v1Tag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckID3v1Tag.setText("yes"); // NOI18N
        jLabelCheckID3v1Tag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckID3v1Tag.setOpaque(true);

        jCheckBoxCheckYearDisplay.setText(bundle.getString("Tag.Year")); // NOI18N

        jCheckBoxCheckGenreDisplay.setText(bundle.getString("Tag.Genre")); // NOI18N

        jLabelCheckYearTag.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckYearTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckYearTag.setText("9999"); // NOI18N
        jLabelCheckYearTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckYearTag.setOpaque(true);

        jLabelCheckGenre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckGenre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckGenre.setText("Genre"); // NOI18N
        jLabelCheckGenre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckGenre.setOpaque(true);

        jLabelCheckNbTracks.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckNbTracks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckNbTracks.setText("99"); // NOI18N
        jLabelCheckNbTracks.setToolTipText(Inter.get("Tooltip.NumberOfMatchTracks")); // NOI18N
        jLabelCheckNbTracks.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckNbTracks.setOpaque(true);

        jLabelCheckNbFiles.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckNbFiles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckNbFiles.setText("99"); // NOI18N
        jLabelCheckNbFiles.setToolTipText(bundle.getString("Tooltip.NumberOfFiles")); // NOI18N
        jLabelCheckNbFiles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckNbFiles.setOpaque(true);

        jCheckCheckTitleDisplay.setText(bundle.getString("Tag.Title")); // NOI18N

        jCheckBoxCheckArtistDisplay.setText(bundle.getString("Tag.Artist")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCheckReplayGain)
                            .addComponent(jLabelCheckID3v1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCheckReplayGainTag, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCheckID3v1Tag, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxCheckBitRateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCheckMeanBitRateTag, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCheckFormatDisplay)
                    .addComponent(jCheckBoxCheckSizeDisplay)
                    .addComponent(jCheckBoxCheckLengthDisplay))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxCheckBPMDisplay)
                        .addGap(57, 57, 57)
                        .addComponent(jLabelCheckNbTracks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCheckNbFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCheckGenreDisplay)
                            .addComponent(jCheckBoxCheckYearDisplay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelCheckYearTag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxCheckCommentDisplay))
                            .addComponent(jLabelCheckGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckCheckTitleDisplay)
                    .addComponent(jCheckBoxCheckArtistDisplay))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxCheckBPMDisplay)
                                    .addComponent(jLabelCheckNbTracks)
                                    .addComponent(jLabelCheckNbFiles))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxCheckGenreDisplay)
                                    .addComponent(jLabelCheckGenre)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckCheckTitleDisplay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxCheckArtistDisplay)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxCheckYearDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCheckYearTag)
                            .addComponent(jCheckBoxCheckCommentDisplay)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCheckReplayGain)
                            .addComponent(jLabelCheckReplayGainTag)
                            .addComponent(jCheckBoxCheckFormatDisplay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCheckID3v1)
                            .addComponent(jLabelCheckID3v1Tag)
                            .addComponent(jCheckBoxCheckSizeDisplay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxCheckBitRateDisplay)
                            .addComponent(jLabelCheckMeanBitRateTag)
                            .addComponent(jCheckBoxCheckLengthDisplay))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(java.awt.Color.lightGray);
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCoverInfo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCoverInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCoverInfo.setText("Cover info"); // NOI18N
        jLabelCoverInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCoverInfo.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jCheckBoxCheckCoverDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCoverInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxCheckCoverDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCoverInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabelCheckDesc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCheckDesc.setText("<html>\nLine1<BR/>\nLine2<BR/>\nLine3<BR/>\n</html>"); // NOI18N
        jLabelCheckDesc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCheckDesc.setOpaque(true);

        jTableCheck.setAutoCreateColumnsFromModel(false);
        jTableCheck.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableCheck.setAutoscrolls(false);
        jScrollPaneCheckTags.setViewportView(jTableCheck);

        jProgressBarCheckDialog.setString("null");
        jProgressBarCheckDialog.setStringPainted(true);

        jComboBoxCheckMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCheckMatchesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCheckTags, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCheckCoverThumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarCheckDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelCheckDesc)
                    .addComponent(jComboBoxCheckMatches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCheckDuplicates, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCheckMatches, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCheckDuplicates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCheckDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCheckCoverThumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBarCheckDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCheckTags, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCheckMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCheckMatchesActionPerformed
        if (jComboBoxCheckMatches.getModel().getSize() > 0) {
            Thread t = new Thread("Thread.PanelCheckDialog.displayMatch") {
                @Override
                public void run() {
                    try {
                        checkDisplay.displayMatch(jComboBoxCheckMatches.getSelectedIndex(), duplicateInfo);
                    } catch (CloneNotSupportedException ex) {
                        //Should never happen since FileInfoDisplay implements Cloneable
                        Jamuz.getLogger().log(Level.SEVERE, "applyMatch()", ex); //NOI18N
                    }
                }
            };
            t.start();
        }
    }//GEN-LAST:event_jComboBoxCheckMatchesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxCheckAlbumArtistDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckAlbumDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckArtistDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckBPMDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckBitRateDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckCommentDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckCoverDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckFormatDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckGenreDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckLengthDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckSizeDisplay;
    private javax.swing.JCheckBox jCheckBoxCheckYearDisplay;
    private javax.swing.JCheckBox jCheckCheckTitleDisplay;
    private javax.swing.JComboBox jComboBoxCheckDuplicates;
    private javax.swing.JComboBox jComboBoxCheckMatches;
    private javax.swing.JLabel jLabelCheckAlbumArtistTag;
    private javax.swing.JLabel jLabelCheckAlbumTag;
    private javax.swing.JLabel jLabelCheckDesc;
    private javax.swing.JLabel jLabelCheckGenre;
    private javax.swing.JLabel jLabelCheckID3v1;
    private javax.swing.JLabel jLabelCheckID3v1Tag;
    private javax.swing.JLabel jLabelCheckMeanBitRateTag;
    private javax.swing.JLabel jLabelCheckNbFiles;
    private javax.swing.JLabel jLabelCheckNbTracks;
    private javax.swing.JLabel jLabelCheckReplayGain;
    private javax.swing.JLabel jLabelCheckReplayGainTag;
    private javax.swing.JLabel jLabelCheckYearTag;
    private javax.swing.JLabel jLabelCoverInfo;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCheckCoverThumb;
    private javax.swing.JProgressBar jProgressBarCheckDialog;
    private javax.swing.JScrollPane jScrollPaneCheckTags;
    private javax.swing.JTable jTableCheck;
    // End of variables declaration//GEN-END:variables

}
