/*
 * Copyright (C) 2012 phramusca <phramusca@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package jamuz.gui;

import jamuz.Jamuz;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;

/**
 * A JDialog extension to display an album cover
 * @author phramusca <phramusca@gmail.com>
 */
public class DialogCoverDisplay extends javax.swing.JDialog {

	private final transient BufferedImage myImage;
	private final int offsetWidth;
	private final int offSetHeight;
	
	/** Creates new CoverDisplayGUI
	 * @param parent 
	 * @param image
	 * @param modal  
	 */
	public DialogCoverDisplay(java.awt.Frame parent, boolean modal, BufferedImage image) {
		super(parent, modal);
		initComponents();
		
		myImage = image;
		
		PanelCover coverImg = (PanelCover) jPanelCover;
		coverImg.setImage(myImage);
		
		jLabelInfo.setText(myImage.getWidth()+"x"+myImage.getHeight());  //NOI18N
		
		offsetWidth = this.getWidth() - jPanelCover.getWidth();
		offSetHeight = this.getHeight() - jPanelCover.getHeight();
		
		resetSize();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonResetSize = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jPanelCover = new jamuz.gui.PanelCover();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonResetSize.setText("1:1"); // NOI18N
        jButtonResetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetSizeActionPerformed(evt);
            }
        });

        jLabelInfo.setText("jLabel1"); // NOI18N

        jPanelCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCover.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanelCover.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanelCover.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanelCoverLayout = new javax.swing.GroupLayout(jPanelCover);
        jPanelCover.setLayout(jPanelCoverLayout);
        jPanelCoverLayout.setHorizontalGroup(
            jPanelCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanelCoverLayout.setVerticalGroup(
            jPanelCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonResetSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResetSize)
                    .addComponent(jLabelInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void resetSize() {
		//TODO: Would be brighter if setting jPanelCover size directly and have JDialog (this) adjusts auto
		//But how to do this ???
		this.setSize(myImage.getWidth()+offsetWidth, myImage.getHeight()+offSetHeight);
	}
	
	private void jButtonResetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetSizeActionPerformed
		resetSize();
	}//GEN-LAST:event_jButtonResetSizeActionPerformed
	
	/**
	 * 
	 * @param myImage 
	 */
	public static void main(final BufferedImage myImage) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {  //NOI18N
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			Jamuz.getLogger().severe(ex.toString());
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				if(myImage!=null) {
					DialogCoverDisplay dialog = new DialogCoverDisplay(new javax.swing.JFrame(), true, myImage );

					//Set dialog to mouse location
					PointerInfo a = MouseInfo.getPointerInfo();
					Point b  = a.getLocation();
					int x = (int)b.getX();
					int y = (int)b.getY();
					//size of the screen
					Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
					if(x + dialog.getWidth()>screenSize.getWidth() ) {
						x=(int)screenSize.getWidth() - dialog.getWidth();
					}
					if(y + dialog.getHeight()>screenSize.getHeight()) {
						y=(int)screenSize.getHeight()- dialog.getHeight();
					}
					dialog.setLocation(x, y);
					dialog.setVisible(true);
				}
			}
		});
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResetSize;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JPanel jPanelCover;
    // End of variables declaration//GEN-END:variables
}
