BEGIN TRANSACTION;
insert into genre ("id", "value") values ('1', 'Blues');
insert into genre ("id", "value") values ('2', 'BO');
insert into genre ("id", "value") values ('3', 'Chanson');
insert into genre ("id", "value") values ('4', 'Dub');
insert into genre ("id", "value") values ('5', 'Electro');
insert into genre ("id", "value") values ('6', 'Folk');
insert into genre ("id", "value") values ('7', 'Funk');
insert into genre ("id", "value") values ('8', 'Jazz');
insert into genre ("id", "value") values ('9', 'Latino');
insert into genre ("id", "value") values ('10', 'Musical');
insert into genre ("id", "value") values ('11', 'Pop');
insert into genre ("id", "value") values ('12', 'Ragga');
insert into genre ("id", "value") values ('13', 'Rap');
insert into genre ("id", "value") values ('14', 'Reggae');
insert into genre ("id", "value") values ('15', 'Reggaeton');
insert into genre ("id", "value") values ('16', 'Rock');
insert into genre ("id", "value") values ('17', 'Salsa');
insert into genre ("id", "value") values ('18', 'Samba');
insert into genre ("id", "value") values ('19', 'Ska');
insert into genre ("id", "value") values ('20', 'Ska Punk');
insert into genre ("id", "value") values ('21', 'Soul');
insert into genre ("id", "value") values ('22', 'Trip Hop');
COMMIT;
