/*
 * Copyright (C) 2016 phramusca ( https://github.com/phramusca/JaMuz/ )
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jamuz.process.video;

import jamuz.Jamuz;
import jamuz.gui.swing.TableModel;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author phramusca ( https://github.com/phramusca/JaMuz/ )
 */
public class DialogVideoCleanupConfirm extends javax.swing.JDialog {

	private static TableModel tableModel;
	private static ArrayList<FileInfoVideo> filesToCleanup;
	/**
	 * Creates new form DialogCleanup
	 * @param parent
	 * @param modal
	 * @param filesToCleanup
	 */
	public DialogVideoCleanupConfirm(java.awt.Frame parent, boolean modal, ArrayList<FileInfoVideo> filesToCleanup) {
		super(parent, modal);
		initComponents();
		
		tableModel = (TableModel) jTableVideoCleanupConfirm.getModel();
		//Set table model
		String[] columnNames = {"Open", "S", "E", "Title", "Filename"};  //NOI18N
		Object[][] data = {
			{"Default", "Default", "Default", "Default", "Default"}  //NOI18N
		};
		tableModel.setModel(columnNames, data);
		//clear the table
        tableModel.clear();
		jTableVideoCleanupConfirm.setEnabled(true);
		
		//Adding columns from model. Cannot be done automatically on properties
		// as done, in initComponents, before setColumnModel which removes the columns ...
		jTableVideoCleanupConfirm.createDefaultColumnsFromModel();
		// Open folder Button
        TableColumn columnButton = jTableVideoCleanupConfirm.getColumnModel().getColumn(0);
        columnButton.setMinWidth(50);
        columnButton.setMaxWidth(200);
        JButton button = new JButton("Open"); //NOI18N
        columnButton.setCellRenderer((JTable table, Object value, boolean isSelected, 
				boolean hasFocus, int row, int column1) -> button);
        columnButton.setCellEditor(new ButtonOpenVideo());
        tableModel.setEditable(new Integer[] {0});
		int maxWidth=30;
        setColumn(1, maxWidth, maxWidth);
        setColumn(2, maxWidth, maxWidth);
		setColumn(3, 150);
		setColumn(4, 500);
		
		DialogVideoCleanupConfirm.filesToCleanup = filesToCleanup;
		display();
		
	}
	
	private static void addRow(FileInfoVideo fileInfoVideo) {
		//"Open", "S", "E", "Title", "Filename"
		Object[] donnee = new Object[]{
			"//"+FilenameUtils.concat(
			Boolean.parseBoolean(Jamuz.getOptions().get("video.library.remote"))?
					Jamuz.getOptions().get("video.location.library")
					:Jamuz.getOptions().get("video.rootPath"), 
			fileInfoVideo.getRelativePath()),
			fileInfoVideo.getSeasonNumber(), 
			fileInfoVideo.getEpisodeNumber(), 
			fileInfoVideo.getTitle(),
			fileInfoVideo.getFilename(),
			};
		tableModel.addRow(donnee);
	}
	
	private void setColumn(int index, int width) {
		setColumn(index, width, -1);
	}
	
	private void setColumn(int index, int width, int maxWidth) {
		TableColumn column = jTableVideoCleanupConfirm.getColumnModel().getColumn(index);
		column.setMinWidth(width);
        column.setPreferredWidth(width);
		column.setWidth(width);
		if(maxWidth>=0)	column.setMaxWidth(maxWidth);
	}
	
	/**
	 *
	 */
	public static void display() {
		jTableVideoCleanupConfirm.setRowSorter(null);
		tableModel.clear();
		for(FileInfoVideo fileInfoVideo : filesToCleanup) {
			addRow(fileInfoVideo);
		}
		//Enable row tableSorter (cannot be done if model is empty)
		if(tableModel.getRowCount()>0) {
			jTableVideoCleanupConfirm.setAutoCreateRowSorter(true);
		}
		else {
			jTableVideoCleanupConfirm.setAutoCreateRowSorter(false);
		}
		jTableVideoCleanupConfirm.setEnabled(true);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVideoDoCleanup = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPaneVideoConfirmCleanup = new javax.swing.JScrollPane();
        jTableVideoCleanupConfirm = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonVideoDoCleanup.setText("Cleanup");
        jButtonVideoDoCleanup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVideoDoCleanupActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jTableVideoCleanupConfirm.setAutoCreateColumnsFromModel(false);
        jTableVideoCleanupConfirm.setModel(new jamuz.gui.swing.TableModel());
        jTableVideoCleanupConfirm.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPaneVideoConfirmCleanup.setViewportView(jTableVideoCleanupConfirm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 583, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVideoDoCleanup))
                    .addComponent(jScrollPaneVideoConfirmCleanup))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneVideoConfirmCleanup, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVideoDoCleanup)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButtonVideoDoCleanupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVideoDoCleanupActionPerformed
        //FIXME VIDEO cleanup: ADD CODE TO DO ACTUAL CLEANUP
    }//GEN-LAST:event_jButtonVideoDoCleanupActionPerformed

	/**
	 * @param filesToCleanup
	 */
	public static void main(ArrayList<FileInfoVideo> filesToCleanup) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogVideoCleanupConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(() -> {
			DialogVideoCleanupConfirm dialog = new DialogVideoCleanupConfirm(new javax.swing.JFrame(), true, filesToCleanup);
			//Center the dialog
			dialog.setLocationRelativeTo(dialog.getParent());
			dialog.setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButtonVideoDoCleanup;
    private javax.swing.JScrollPane jScrollPaneVideoConfirmCleanup;
    private static javax.swing.JTable jTableVideoCleanupConfirm;
    // End of variables declaration//GEN-END:variables
}
