name: Local runner temp job

on:
  workflow_dispatch:
  push:
    branches:
      - 'robot*'

jobs:
  build:

    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Create dist
      run: |
        mkdir dist
        cp -r target/JaMuz-jar-with-dependencies.jar dist/JaMuz.jar
        cp -r target-data/* dist
      working-directory: ${{ github.workspace }}
    
    - name: Create JaMuz.db & myMovieDb.db in dist
      run: |
        sqlite3 dist/JaMuz.db  # Create an empty database if it doesn't exist
        sqlite3 dist/JaMuz.db < database/JaMuz_creation.sql
        sqlite3 dist/JaMuz.db < database/JaMuz_insertion_minimal.sql
        sqlite3 dist/JaMuz.db < database/JaMuz_insertion_optional.sql
        sqlite3 dist/myMovieDb.db  # Create an empty database if it doesn't exist
        sqlite3 dist/myMovieDb.db < database/myMovieDb_creation.sql
      working-directory: ${{ github.workspace }}

    - name: Copy dist to Windows
      run: |
        cp -r dist /mnt/c
      working-directory: ${{ github.workspace }}
