name: Java CI with Maven

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  #pull_request:
  #  branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Setup SQLite
      run: |
        sudo apt-get update -y
        sudo apt-get install sqlite3 -y
      shell: bash

    - name: Create dist
      run: |
        mkdir dist
        cp -r target/JaMuz-jar-with-dependencies.jar dist/JaMuz.jar
        cp -r target-data/* dist
      working-directory: ${{ github.workspace }}

    - name: Create JaMuz.db & myMovieDb.db in dist
      run: |
        sqlite3 dist/JaMuz.db  # Create an empty database if it doesn't exist
        sqlite3 dist/JaMuz.db < database/JaMuz_creation.sql
        sqlite3 dist/JaMuz.db < database/JaMuz_insertion_minimal.sql
        sqlite3 dist/JaMuz.db < database/JaMuz_insertion_optional.sql
        sqlite3 dist/myMovieDb.db  # Create an empty database if it doesn't exist
        sqlite3 dist/myMovieDb.db < database/myMovieDb_creation.sql
      working-directory: ${{ github.workspace }}

    - name: 7zip dist
      run: |
        mv dist JaMuz
        7z a -r JaMuz_${{ github.ref_name }}.7z JaMuz
 
    # - name: List Workspace Directory
    #   run: ls -la ${{ github.workspace }}
   
    - name: Extract body from CHANGELOG
      id: extract_body
      run: |
        current_version="${{ github.ref_name }}"
        awk_script='$0 ~ "^## " version {p=1} p && !/^## / {print}'
        RELEASE_BODY=$(awk -v version="${current_version}" '$0 ~ "^## " version {p=1; next} p && /^## / {p=0} p {print}' CHANGELOG.md)
        echo "$RELEASE_BODY" > release_body.txt
      shell: bash

    - name: Publish Release
      id: publish_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          JaMuz_${{ github.ref_name }}.7z
        tag_name: ${{ github.ref_name }}
        name: JaMuz Desktop ${{ github.ref_name }}
        body_path: ${{ github.workspace }}/release_body.txt
        draft: true
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
