name: Maven GPT

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can change the Java version as needed

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./  # Adjust the path if your POM file is in a subdirectory

    - name: Upload JAR file
      if: success()  # Only upload the JAR file if the build succeeds
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/*.jar  # Modify the path to match your artifact name
